# AI
langchain4j:
  open-ai:
    chat-model:
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
      base-url: https://api.deepseek.com
      api-key:自己的api key
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
